### ISSUE TITLE
Duplication glitch with router reborn.

### ISSUE THREAD

**Issue by Eidelmaim** [MdLenoman/EssentialCraft-3#1]
this is a duplication glitch discovered using router reborn and EC3, this is on a live Horizons Daybreaker server using Kcauldron, more information in the video.

https://www.youtube.com/watch?v=-JdzFxS2V64&feature=youtu.be

**Comment by 3TUSK** [comment]
Are you sure you find the correct repository? I gonna say you need to report bug [here](https://github.com/Modbder/EssentialCraft3/issues)

**Comment by Eidelmaim** [comment]
thank you for pointing me to the correct repository. you can close this
